name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (optional)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  # Cache gradle downloads (optional)

      - name: Set up Android SDK
        uses: actions/setup-android-sdk@v3
        with:
          # List of required SDK components
          sdk-components: platform-tools, build-tools, tools, emulator, system-images;android-30;google_apis;x86_64

          # Optional: Cache downloaded components for faster builds
          cache: 'android-sdk'

      - name: Print ANDROID_HOME and PATH (optional, for troubleshooting)
        run: echo $ANDROID_HOME && echo $PATH

      # Rest of your existing workflow steps...

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumented tests
        run: ./gradlew connectedAndroidTest

      - name: Stop the emulator
        run: adb -s emulator-5554 emu kill