name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
          mkdir -p $HOME/android-sdk
          unzip -q android-sdk-tools.zip -d $HOME/android-sdk
          # Update path based on unzip output (replace with actual path)
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$HOME/android-sdk/<actual_path_to_cmdline_tools_bin>:$PATH
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/<actual_path_to_cmdline_tools_bin>:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumented tests
        run: ./gradlew connectedAndroidTest

      - name: Stop the emulator
        run: adb -s emulator-5554 emu kill
